### ISSUE TITLE
make_travis_yml_2.hs doesn't build with GHC 8.4.1

### ISSUE THREAD

**Issue by RyanGlScott** [haskell-CI/haskell-ci#145]
```
$ ~/Software/ghc-8.4.1/bin/runghc ../haskell-ci/make_travis_yml_2.hs '-o' '.travis.yml' 'cabal.project'

../haskell-ci/make_travis_yml_2.hs:70:1: error:
    Could not find module ‘Distribution.PackageDescription.Parse’
    Perhaps you meant
      Distribution.PackageDescription.Parsec (from Cabal-2.2.0.0)
      Distribution.PackageDescription.Check (from Cabal-2.2.0.0)
      Distribution.PackageDescription.Quirks (from Cabal-2.2.0.0)
    Use -v to see a list of the files searched for.
   |
70 | import Distribution.PackageDescription.Parse (readGenericPackageDescription)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by RyanGlScott** [comment]
Oops, I didn't notice https://github.com/haskell-CI/haskell-ci/pull/138. I'll close this in favor of that.
