### ISSUE TITLE
Second script failed compile on ghc-8.4.3

### ISSUE THREAD

**Issue by thisiswhereitype** [haskell-CI/haskell-ci#175]
Switching to `ghc-8.2.2` generates a `.travis.yml`.

```haskell
 $ runghc ../haskell-ci/make_travis_yml_2.hs '--osx=8.4.3' 'pangraph.cabal' '-o' '.travis.yml'
Loaded package environment from ../git/pangraph/.ghc.environment.x86_64-linux-8.4.3

../haskell-ci/make_travis_yml_2.hs:60:1: error:
    Could not find module ‘Distribution.Compiler’
    Use -v to see a list of the files searched for.
   |
60 | import Distribution.Compiler (CompilerFlavor(..))
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

../haskell-ci/make_travis_yml_2.hs:61:1: error:
    Could not find module ‘Distribution.Package’
    Use -v to see a list of the files searched for.
   |
61 | import Distribution.Package hiding (Package, pkgName)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

../haskell-ci/make_travis_yml_2.hs:62:1: error:
    Could not find module ‘Distribution.Package’
    Use -v to see a list of the files searched for.
   |
62 | import qualified Distribution.Package as Pkg
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

../haskell-ci/make_travis_yml_2.hs:63:1: error:
    Could not find module ‘Distribution.PackageDescription’
    Use -v to see a list of the files searched for.
   |
63 | import Distribution.PackageDescription (GenericPackageDescription,packageDescription, testedWith, package, condLibrary, condTestSuites)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

../haskell-ci/make_travis_yml_2.hs:64:1: error:
    Could not find module ‘Distribution.PackageDescription.Configuration’
    Use -v to see a list of the files searched for.
   |
64 | import Distribution.PackageDescription.Configuration (flattenPackageDescription)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

../haskell-ci/make_travis_yml_2.hs:65:1: error:
    Could not find module ‘Distribution.PackageDescription’
    Use -v to see a list of the files searched for.
   |
65 | import qualified Distribution.PackageDescription as PD
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

../haskell-ci/make_travis_yml_2.hs:66:1: error:
    Could not find module ‘Distribution.ParseUtils’
    Use -v to see a list of the files searched for.
   |
66 | import qualified Distribution.ParseUtils as PU
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

../haskell-ci/make_travis_yml_2.hs:67:1: error:
    Could not find module ‘Distribution.Text’
    Use -v to see a list of the files searched for.
   |
67 | import Distribution.Text
   | ^^^^^^^^^^^^^^^^^^^^^^^^

../haskell-ci/make_travis_yml_2.hs:68:1: error:
    Could not find module ‘Distribution.Version’
    Use -v to see a list of the files searched for.
   |
68 | import Distribution.Version
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^

../haskell-ci/make_travis_yml_2.hs:74:1: error:
    Could not find module ‘Distribution.PackageDescription.Parse’
    Use -v to see a list of the files searched for.
   |
74 | import Distribution.PackageDescription.Parse (readPackageDescription)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

../haskell-ci/make_travis_yml_2.hs:75:1: error:
    Could not find module ‘Distribution.Verbosity’
    Use -v to see a list of the files searched for.
   |
75 | import Distribution.Verbosity (Verbosity)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

../haskell-ci/make_travis_yml_2.hs:77:1: error:
    Could not find module ‘Distribution.Compat.ReadP’
    Use -v to see a list of the files searched for.
   |
77 | import Distribution.Compat.ReadP
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```

**Comment by phadej** [comment]
Probably there's some local environment, either sandbox or `.ghc.environment` files in the directory, messing up the setup.

I'd recommend to install `make-travis-yml` as an executable. With #174 (we are discussing about the name of executable, and its UI) that would be the only way to use *Haskell-CI*

**Comment by thisiswhereitype** [comment]
Yes the environment file appeared to be the issue, thanks!
