### ISSUE TITLE
Can't compile with GHC 9.2.1

### ISSUE THREAD

**Issue by LeventErkok** [haskell-CI/haskell-ci#557]
```
[23 of 42] Compiling HaskellCI.Compiler

src/HaskellCI/Compiler.hs:28:45: error:
    Module ‘Distribution.Version’ does not export ‘invertVersionRange’
   |
28 | import Distribution.Version (hasUpperBound, invertVersionRange, versionNumbers, withinRange)
   |                                             ^^^^^^^^^^^^^^^^^^
cabal: Failed to build lib:haskell-ci-internal from haskell-ci-0.12.1 (which
is required by exe:haskell-ci from haskell-ci-0.12.1). See the build log above
for details.

cabal new-install haskell-ci  253.30s user 27.89s system 168% cpu 2:47.07 total
```
